from typing import Protocol
from uuid import UUID

from personlogy.domain.job import Job
from personlogy.domain.knowledge.models import Citation, Claim, KnowledgeNode
from personlogy.domain.relation.models import Relation, RelationType
from personlogy.domain.source.models import ContentBlock, Project, Source, SourceVersion


class SourceRepository(Protocol):
    async def add_project(self, project: Project) -> None: ...

    async def add_source(self, source: Source) -> None: ...

    async def add_version(self, version: SourceVersion) -> None: ...

    async def add_block(self, block: ContentBlock) -> None: ...


class KnowledgeRepository(Protocol):
    async def add_node(self, node: KnowledgeNode) -> None: ...

    async def add_citation(self, citation: Citation) -> None: ...

    async def add_claim(self, claim: Claim) -> None: ...

    async def add_relation(self, relation: Relation) -> None: ...

    async def add_relation_type(self, relation_type: RelationType) -> None: ...


class JobRepository(Protocol):
    async def add(self, job: Job) -> None: ...

    async def save(self, job: Job) -> None: ...

    async def get(self, job_id: UUID) -> Job | None: ...

    async def get_by_idempotency_key(self, key: str) -> Job | None: ...

    async def list(self, *, limit: int = 100) -> list[Job]: ...
