from typing import Protocol
from uuid import UUID

from personlogy.domain.governance.models import (
    ConflictRecord,
    DuplicateGroup,
    GovernanceIssue,
    GovernanceRun,
    ReviewTask,
)
from personlogy.domain.job import Job
from personlogy.domain.knowledge.models import Citation, Claim, KnowledgeNode
from personlogy.domain.relation.models import Relation, RelationType
from personlogy.domain.source.conversation import Conversation, ConversationMessage
from personlogy.domain.source.models import (
    ContentBlock,
    Project,
    Source,
    SourceKind,
    SourceVersion,
)


class SourceRepository(Protocol):
    async def add_project(self, project: Project) -> None: ...
    async def get_project_by_slug(self, slug: str) -> Project | None: ...

    async def add_source(self, source: Source) -> None: ...
    async def get_source(
        self, project_id: UUID, kind: SourceKind, title: str
    ) -> Source | None: ...

    async def add_conversation(self, conversation: Conversation) -> None: ...
    async def get_conversation(self, project_id: UUID, external_id: str) -> Conversation | None: ...
    async def add_message(self, message: ConversationMessage) -> None: ...
    async def get_message(
        self, conversation_id: UUID, external_id: str
    ) -> ConversationMessage | None: ...

    async def add_version(self, version: SourceVersion) -> None: ...
    async def get_version(self, version_id: UUID) -> SourceVersion | None: ...
    async def get_version_in_project(
        self, project_id: UUID, version_id: UUID
    ) -> SourceVersion | None: ...
    async def get_pdf_version_by_hash(
        self, project_id: UUID, content_hash: str
    ) -> SourceVersion | None: ...
    async def next_version_number(self, source_id: UUID) -> int: ...

    async def add_block(self, block: ContentBlock) -> None: ...
    async def get_block(self, block_id: UUID) -> ContentBlock | None: ...
    async def list_blocks(self, source_version_id: UUID) -> list[ContentBlock]: ...


class KnowledgeRepository(Protocol):
    async def add_node(self, node: KnowledgeNode) -> None: ...

    async def get_node(self, node_id: UUID) -> KnowledgeNode | None: ...

    async def save_node(self, node: KnowledgeNode) -> None: ...

    async def add_citation(self, citation: Citation) -> None: ...

    async def get_citation(self, citation_id: UUID) -> Citation | None: ...

    async def add_claim(self, claim: Claim) -> None: ...

    async def get_claim(self, claim_id: UUID) -> Claim | None: ...

    async def save_claim(self, claim: Claim) -> None: ...

    async def add_relation(self, relation: Relation) -> None: ...

    async def get_relation(self, relation_id: UUID) -> Relation | None: ...

    async def save_relation(self, relation: Relation) -> None: ...

    async def add_relation_type(self, relation_type: RelationType) -> None: ...

    async def get_relation_type(self, key: str) -> RelationType | None: ...


class GovernanceRepository(Protocol):
    async def add_run(self, run: GovernanceRun) -> None: ...

    async def add_issue(self, issue: GovernanceIssue) -> None: ...

    async def add_duplicate_group(self, group: DuplicateGroup) -> None: ...

    async def add_conflict(self, conflict: ConflictRecord) -> None: ...

    async def add_review_task(self, task: ReviewTask) -> None: ...

    async def get_review_task(self, task_id: UUID) -> ReviewTask | None: ...

    async def save_review_task(self, task: ReviewTask) -> None: ...

    async def list_review_tasks(self, *, limit: int = 100) -> list[ReviewTask]: ...


class JobRepository(Protocol):
    async def add(self, job: Job) -> None: ...

    async def save(self, job: Job) -> None: ...

    async def get(self, job_id: UUID) -> Job | None: ...

    async def get_by_idempotency_key(self, key: str) -> Job | None: ...

    async def list(self, *, limit: int = 100) -> list[Job]: ...
