# Gel migration workflow script (PersonLogy)
#
# Usage (run from repo root):
#   .\GEL\scripts\gel-migrate.ps1                 # apply existing migrations only
#   .\GEL\scripts\gel-migrate.ps1 -Create          # apply + generate new migration from dbschema diff
#   .\GEL\scripts\gel-migrate.ps1 -Create -Seed    # apply + generate + run seed
#   .\GEL\scripts\gel-migrate.ps1 -Password xxxx   # pass password via stdin (default: $env:GEL_PASSWORD)
#
# Prerequisites:
#   - Gel CLI on PATH or $env:GEL_CLI pointing to gel.exe (>= 7.x)
#   - Target Gel server running; DSN defaults to the personlogy database
#   - Database has allow_user_specified_id enabled (domain UUIDs are generated by Python)
#
# Note: migration files must be generated by the CLI; hand-written migration names
# cannot be parsed (see "Known pitfalls" in GEL/README.md).
#
# Gel writes a version-check warning to stderr on every invocation; that is
# expected noise, so the script runs with $ErrorActionPreference = "Continue"
# and inspects $LASTEXITCODE explicitly.

param(
    [switch]$Create,
    [switch]$Seed,
    [string]$Password = $env:GEL_PASSWORD,
    [string]$Dsn = "gel://edgedb@localhost:5656/personlogy",
    [switch]$AllowInsecureLocal
)

$ErrorActionPreference = "Continue"

# --- locate CLI ---
$cli = $null
if ($env:GEL_CLI -and (Test-Path $env:GEL_CLI)) {
    $cli = $env:GEL_CLI
} elseif (Get-Command gel -ErrorAction SilentlyContinue) {
    $cli = (Get-Command gel).Source
} elseif (Test-Path "$env:APPDATA\edgedb\bin\gel.exe") {
    $cli = "$env:APPDATA\edgedb\bin\gel.exe"
}
if (-not $cli) {
    Write-Error "Gel CLI not found. Install Gel CLI or set `$env:GEL_CLI."
    exit 1
}
Write-Host "Gel CLI: $cli"

# --- resolve connection arguments without putting credentials in the DSN ---
$connectionArgs = @("--dsn", $Dsn)
if ($AllowInsecureLocal) {
    $connectionArgs += @("--tls-security", "insecure")
}
if ($Password) {
    $connectionArgs += "--password-from-stdin"
}
if (-not $Password) {
    Write-Warning "No password provided (-Password or `$env:GEL_PASSWORD). Ignore if the instance has none."
}

$repoRoot = (Get-Location).Path
$gelDir = Join-Path $repoRoot "GEL"
if (-not (Test-Path (Join-Path $gelDir "dbschema\default.gel"))) {
    Write-Error "dbschema\default.gel not found under $gelDir. Run from the repo root."
    exit 1
}

function Invoke-GelMigrate {
    param([string]$Label)
    Write-Host ""
    Write-Host "==> $Label"
    Push-Location $gelDir
    try {
        if ($Password) { $Password | & $cli migrate @connectionArgs 2>$null }
        else { & $cli migrate @connectionArgs 2>$null }
        if ($LASTEXITCODE -ne 0) { throw "gel migrate failed: $Label (exit $LASTEXITCODE)" }
    } finally {
        Pop-Location
    }
}

function Invoke-GelCreate {
    Write-Host ""
    Write-Host "==> Generate new migration from dbschema diff"
    Push-Location $gelDir
    try {
        if ($Password) { $Password | & $cli migration create @connectionArgs --non-interactive 2>$null }
        else { & $cli migration create @connectionArgs --non-interactive 2>$null }
        if ($LASTEXITCODE -eq 4) {
            Write-Host "  -> no schema changes; nothing to generate"
        } elseif ($LASTEXITCODE -ne 0) {
            throw "gel migration create failed (exit $LASTEXITCODE)"
        }
    } finally {
        Pop-Location
    }
}

function Invoke-GelSeed {
    Write-Host ""
    Write-Host "==> Run seed (RelationType initialization)"
    Push-Location $gelDir
    try {
        if ($Password) { $Password | & $cli query @connectionArgs -f seed.edgeql 2>$null }
        else { & $cli query @connectionArgs -f seed.edgeql 2>$null }
        if ($LASTEXITCODE -ne 0) { throw "gel seed failed (exit $LASTEXITCODE)" }
    } finally {
        Pop-Location
    }
}

function Assert-GelConfig {
    Write-Host ""
    Write-Host "==> Check allow_user_specified_id"
    if ($Password) {
        $result = ($Password | & $cli query @connectionArgs `
        "select cfg::Config { allow_user_specified_id }" 2>$null | Out-String)
    } else {
        $result = (& $cli query @connectionArgs `
        "select cfg::Config { allow_user_specified_id }" 2>$null | Out-String)
    }
    if ($result -notmatch "true") {
        Write-Host "  -> not enabled; attempting to enable (needs superuser, fall back to manual)"
        if ($Password) {
            $Password | & $cli query @connectionArgs `
                "configure current database set allow_user_specified_id := true" 2>$null | Out-Null
        } else {
            & $cli query @connectionArgs `
                "configure current database set allow_user_specified_id := true" 2>$null | Out-Null
        }
    } else {
        Write-Host "  -> enabled"
    }
}

# --- main ---
Invoke-GelMigrate "Apply existing migrations (00001..N)"
if ($Create) {
    Invoke-GelCreate
    Invoke-GelMigrate "Apply newly generated migration"
}
if ($Seed) {
    Invoke-GelSeed
}
Assert-GelConfig

Write-Host ""
Write-Host "Applied migrations:"
if ($Password) { $Password | & $cli query @connectionArgs "select schema::Migration.name" 2>$null }
else { & $cli query @connectionArgs "select schema::Migration.name" 2>$null }

Write-Host ""
Write-Host "Tip: if the CLI reports 'cannot parse migration name', a hand-written migration"
Write-Host "file exists. Delete it and rerun with -Create to regenerate from the baseline"
Write-Host "(see 'Known pitfalls' in GEL/README.md)."
