# ruff: noqa: E501
"""Create the authoritative knowledge-store schema.

Revision ID: 20260728_0001
Revises: None
Create Date: 2026-07-28
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260728_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(sa.text('CREATE EXTENSION IF NOT EXISTS pg_trgm'))
    op.execute(sa.text("CREATE TABLE audit_log (\n\tcommand VARCHAR(100) NOT NULL, \n\tactor VARCHAR(100) NOT NULL, \n\ttarget_kind VARCHAR(15) NOT NULL, \n\ttarget_id UUID NOT NULL, \n\tbefore JSONB, \n\tafter JSONB, \n\treason TEXT NOT NULL, \n\trequest_id VARCHAR(100), \n\toccurred_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tid UUID NOT NULL, \n\tCONSTRAINT pk_audit_log PRIMARY KEY (id), \n\tCONSTRAINT ck_audit_log_audit_target_kind CHECK (target_kind IN ('object', 'relation', 'source_document', 'evidence', 'claim', 'decision', 'candidate'))\n)"))
    op.execute(sa.text('CREATE INDEX ix_audit_log_occurred_at ON audit_log (occurred_at)'))
    op.execute(sa.text('CREATE INDEX ix_audit_log_target ON audit_log (target_kind, target_id)'))
    op.execute(sa.text("CREATE TABLE graph_projection_checkpoint (\n\tmapping_version VARCHAR(50) NOT NULL, \n\tprojection_version INTEGER DEFAULT '0' NOT NULL, \n\tstatus VARCHAR(9) DEFAULT 'pending' NOT NULL, \n\tlast_event_id UUID, \n\tprojected_at TIMESTAMP WITH TIME ZONE, \n\tlast_validated_at TIMESTAMP WITH TIME ZONE, \n\tobject_count INTEGER DEFAULT '0' NOT NULL, \n\trelation_count INTEGER DEFAULT '0' NOT NULL, \n\tvalidation_diff JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_graph_projection_checkpoint PRIMARY KEY (id), \n\tCONSTRAINT ck_graph_projection_checkpoint_projection_version_nonnegative CHECK (projection_version >= 0), \n\tCONSTRAINT ck_graph_projection_checkpoint_object_count_nonnegative CHECK (object_count >= 0), \n\tCONSTRAINT ck_graph_projection_checkpoint_relation_count_nonnegative CHECK (relation_count >= 0), \n\tCONSTRAINT uq_graph_projection_checkpoint_mapping UNIQUE (mapping_version), \n\tCONSTRAINT ck_graph_projection_checkpoint_checkpoint_projection_status CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'degraded'))\n)"))
    op.execute(sa.text("CREATE TABLE graph_projection_event (\n\taggregate_kind VARCHAR(15) NOT NULL, \n\taggregate_id UUID NOT NULL, \n\tevent_type VARCHAR(7) NOT NULL, \n\ttarget_version INTEGER NOT NULL, \n\tmapping_version VARCHAR(50) NOT NULL, \n\tstatus VARCHAR(9) DEFAULT 'pending' NOT NULL, \n\tpayload JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tattempt_count INTEGER DEFAULT '0' NOT NULL, \n\terror_summary TEXT, \n\tavailable_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tprocessed_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_graph_projection_event PRIMARY KEY (id), \n\tCONSTRAINT ck_graph_projection_event_target_version_positive CHECK (target_version >= 1), \n\tCONSTRAINT ck_graph_projection_event_attempt_count_nonnegative CHECK (attempt_count >= 0), \n\tCONSTRAINT uq_graph_projection_event_idempotency UNIQUE (aggregate_kind, aggregate_id, event_type, target_version, mapping_version), \n\tCONSTRAINT ck_graph_projection_event_projection_aggregate_kind CHECK (aggregate_kind IN ('object', 'relation', 'source_document', 'evidence', 'claim', 'decision', 'candidate')), \n\tCONSTRAINT ck_graph_projection_event_projection_event_type CHECK (event_type IN ('publish', 'revise', 'archive', 'restore')), \n\tCONSTRAINT ck_graph_projection_event_projection_status CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'degraded'))\n)"))
    op.execute(sa.text('CREATE INDEX ix_graph_projection_event_pending ON graph_projection_event (status, available_at, created_at)'))
    op.execute(sa.text("CREATE TABLE knowledge_object (\n\tobject_type VARCHAR(10) NOT NULL, \n\tcanonical_name VARCHAR(255) NOT NULL, \n\tdisplay_name VARCHAR(255) NOT NULL, \n\tstatus VARCHAR(10) NOT NULL, \n\taliases JSONB DEFAULT '[]'::jsonb NOT NULL, \n\tattributes JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tvisibility VARCHAR(9) DEFAULT 'private' NOT NULL, \n\tversion INTEGER DEFAULT '1' NOT NULL, \n\tvalid_from TIMESTAMP WITH TIME ZONE, \n\tvalid_to TIMESTAMP WITH TIME ZONE, \n\tcaptured_at TIMESTAMP WITH TIME ZONE, \n\tverified_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by VARCHAR(100) NOT NULL, \n\treviewed_by VARCHAR(100), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_knowledge_object PRIMARY KEY (id), \n\tCONSTRAINT ck_knowledge_object_version_positive CHECK (version >= 1), \n\tCONSTRAINT ck_knowledge_object_object_type CHECK (object_type IN ('company', 'department', 'position', 'jd_version', 'skill', 'experience')), \n\tCONSTRAINT ck_knowledge_object_object_status CHECK (status IN ('draft', 'active', 'inactive', 'unknown', 'closed', 'current', 'historical', 'disputed', 'merged', 'verified', 'archived')), \n\tCONSTRAINT ck_knowledge_object_visibility CHECK (visibility IN ('public', 'private', 'sensitive'))\n)"))
    op.execute(sa.text('CREATE INDEX ix_knowledge_object_canonical_name_trgm ON knowledge_object USING gin (canonical_name gin_trgm_ops)'))
    op.execute(sa.text('CREATE INDEX ix_knowledge_object_type_status ON knowledge_object (object_type, status)'))
    op.execute(sa.text("CREATE TABLE object_version (\n\taggregate_kind VARCHAR(15) NOT NULL, \n\taggregate_id UUID NOT NULL, \n\tversion INTEGER NOT NULL, \n\tsnapshot JSONB NOT NULL, \n\treason TEXT NOT NULL, \n\tcreated_by VARCHAR(100) NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tid UUID NOT NULL, \n\tCONSTRAINT pk_object_version PRIMARY KEY (id), \n\tCONSTRAINT ck_object_version_version_positive CHECK (version >= 1), \n\tCONSTRAINT uq_object_version_aggregate_version UNIQUE (aggregate_kind, aggregate_id, version), \n\tCONSTRAINT ck_object_version_version_aggregate_kind CHECK (aggregate_kind IN ('object', 'relation', 'source_document', 'evidence', 'claim', 'decision', 'candidate'))\n)"))
    op.execute(sa.text('CREATE INDEX ix_object_version_aggregate ON object_version (aggregate_kind, aggregate_id)'))
    op.execute(sa.text("CREATE TABLE processing_job (\n\tjob_type VARCHAR(16) NOT NULL, \n\tstatus VARCHAR(9) DEFAULT 'pending' NOT NULL, \n\tinput_reference JSONB NOT NULL, \n\tresult_summary JSONB, \n\tattempt_count INTEGER DEFAULT '0' NOT NULL, \n\tmax_attempts INTEGER DEFAULT '3' NOT NULL, \n\terror_summary TEXT, \n\tlease_owner VARCHAR(100), \n\tlease_expires_at TIMESTAMP WITH TIME ZONE, \n\tnext_attempt_at TIMESTAMP WITH TIME ZONE, \n\tstarted_at TIMESTAMP WITH TIME ZONE, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_processing_job PRIMARY KEY (id), \n\tCONSTRAINT ck_processing_job_attempt_count_nonnegative CHECK (attempt_count >= 0), \n\tCONSTRAINT ck_processing_job_max_attempts_positive CHECK (max_attempts >= 1), \n\tCONSTRAINT ck_processing_job_job_type CHECK (job_type IN ('source_parse', 'llm_extract', 'impact_analysis', 'graph_projection', 'graph_validation', 'graph_rebuild')), \n\tCONSTRAINT ck_processing_job_job_status CHECK (status IN ('pending', 'running', 'succeeded', 'failed', 'cancelled'))\n)"))
    op.execute(sa.text('CREATE INDEX ix_processing_job_claim ON processing_job (status, next_attempt_at, created_at)'))
    op.execute(sa.text('CREATE INDEX ix_processing_job_lease ON processing_job (status, lease_expires_at)'))
    op.execute(sa.text("CREATE TABLE source_document (\n\ttitle VARCHAR(500) NOT NULL, \n\tsource_type VARCHAR(8) NOT NULL, \n\tsource_url TEXT, \n\tstorage_path TEXT, \n\traw_text TEXT, \n\tcontent_fingerprint VARCHAR(64) NOT NULL, \n\tcontent_size INTEGER DEFAULT '0' NOT NULL, \n\tstatus VARCHAR(18) DEFAULT 'captured' NOT NULL, \n\tvisibility VARCHAR(9) DEFAULT 'private' NOT NULL, \n\tmetadata JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tcaptured_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tversion INTEGER DEFAULT '1' NOT NULL, \n\tcreated_by VARCHAR(100) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_source_document PRIMARY KEY (id), \n\tCONSTRAINT ck_source_document_version_positive CHECK (version >= 1), \n\tCONSTRAINT ck_source_document_content_size_nonnegative CHECK (content_size >= 0), \n\tCONSTRAINT ck_source_document_source_type CHECK (source_type IN ('text', 'web', 'pdf', 'markdown', 'image', 'other')), \n\tCONSTRAINT ck_source_document_source_status CHECK (status IN ('captured', 'parsed', 'parse_failed', 'source_unreachable', 'archived')), \n\tCONSTRAINT ck_source_document_source_visibility CHECK (visibility IN ('public', 'private', 'sensitive'))\n)"))
    op.execute(sa.text('CREATE INDEX ix_source_document_fingerprint ON source_document (content_fingerprint)'))
    op.execute(sa.text('CREATE INDEX ix_source_document_status_captured ON source_document (status, captured_at)'))
    op.execute(sa.text("CREATE TABLE candidate (\n\tcandidate_kind VARCHAR(9) NOT NULL, \n\tstatus VARCHAR(14) DEFAULT 'pending_review' NOT NULL, \n\tpayload JSONB NOT NULL, \n\tsource_document_id UUID, \n\tcreated_by VARCHAR(100) NOT NULL, \n\treviewed_by VARCHAR(100), \n\treviewed_at TIMESTAMP WITH TIME ZONE, \n\trejection_reason TEXT, \n\tpublished_target_kind VARCHAR(15), \n\tpublished_target_id UUID, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_candidate PRIMARY KEY (id), \n\tCONSTRAINT ck_candidate_candidate_kind CHECK (candidate_kind IN ('object', 'attribute', 'relation', 'claim', 'evidence')), \n\tCONSTRAINT ck_candidate_candidate_status CHECK (status IN ('pending_review', 'accepted', 'rejected', 'merged')), \n\tCONSTRAINT fk_candidate_source_document_id_source_document FOREIGN KEY(source_document_id) REFERENCES source_document (id) ON DELETE RESTRICT, \n\tCONSTRAINT ck_candidate_candidate_published_target_kind CHECK (published_target_kind IN ('object', 'relation', 'source_document', 'evidence', 'claim', 'decision', 'candidate'))\n)"))
    op.execute(sa.text('CREATE INDEX ix_candidate_source ON candidate (source_document_id)'))
    op.execute(sa.text('CREATE INDEX ix_candidate_status_kind ON candidate (status, candidate_kind)'))
    op.execute(sa.text("CREATE TABLE claim (\n\tsubject_object_id UUID NOT NULL, \n\tcontent TEXT NOT NULL, \n\tepistemic_type VARCHAR(17) NOT NULL, \n\tstatus VARCHAR(12) DEFAULT 'draft' NOT NULL, \n\tfreshness VARCHAR(18) DEFAULT 'fresh' NOT NULL, \n\tscope JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tconfidence_note TEXT, \n\tvalid_from TIMESTAMP WITH TIME ZONE, \n\tvalid_to TIMESTAMP WITH TIME ZONE, \n\tconfirmed_at TIMESTAMP WITH TIME ZONE, \n\tversion INTEGER DEFAULT '1' NOT NULL, \n\tcreated_by VARCHAR(100) NOT NULL, \n\treviewed_by VARCHAR(100), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_claim PRIMARY KEY (id), \n\tCONSTRAINT ck_claim_version_positive CHECK (version >= 1), \n\tCONSTRAINT fk_claim_subject_object_id_knowledge_object FOREIGN KEY(subject_object_id) REFERENCES knowledge_object (id) ON DELETE RESTRICT, \n\tCONSTRAINT ck_claim_claim_epistemic_type CHECK (epistemic_type IN ('direct_fact', 'source_assertion', 'derived_inference', 'personal_judgment')), \n\tCONSTRAINT ck_claim_claim_status CHECK (status IN ('draft', 'confirmed', 'disputed', 'needs_review', 'superseded', 'archived')), \n\tCONSTRAINT ck_claim_claim_freshness CHECK (freshness IN ('fresh', 'verification_due', 'stale', 'source_unreachable', 'superseded'))\n)"))
    op.execute(sa.text('CREATE INDEX ix_claim_freshness ON claim (freshness)'))
    op.execute(sa.text('CREATE INDEX ix_claim_subject_status ON claim (subject_object_id, status)'))
    op.execute(sa.text("CREATE TABLE decision (\n\ttarget_object_id UUID NOT NULL, \n\tdecision_type VARCHAR(12) NOT NULL, \n\tstatus VARCHAR(12) DEFAULT 'proposed' NOT NULL, \n\treason TEXT NOT NULL, \n\tdecided_at TIMESTAMP WITH TIME ZONE, \n\treview_at TIMESTAMP WITH TIME ZONE, \n\tversion INTEGER DEFAULT '1' NOT NULL, \n\tcreated_by VARCHAR(100) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_decision PRIMARY KEY (id), \n\tCONSTRAINT ck_decision_version_positive CHECK (version >= 1), \n\tCONSTRAINT fk_decision_target_object_id_knowledge_object FOREIGN KEY(target_object_id) REFERENCES knowledge_object (id) ON DELETE RESTRICT, \n\tCONSTRAINT ck_decision_decision_type CHECK (decision_type IN ('focus_apply', 'normal_apply', 'defer', 'abandon', 'prepare')), \n\tCONSTRAINT ck_decision_decision_status CHECK (status IN ('proposed', 'confirmed', 'revised', 'abandoned', 'completed', 'needs_review', 'archived'))\n)"))
    op.execute(sa.text('CREATE INDEX ix_decision_review_at ON decision (review_at)'))
    op.execute(sa.text('CREATE INDEX ix_decision_target_status ON decision (target_object_id, status)'))
    op.execute(sa.text("CREATE TABLE evidence (\n\tsource_document_id UUID NOT NULL, \n\texcerpt TEXT NOT NULL, \n\tlocator JSONB DEFAULT '{}'::jsonb NOT NULL, \n\tcontent_fingerprint VARCHAR(64) NOT NULL, \n\tsource_level VARCHAR(50), \n\tstatus VARCHAR(15) DEFAULT 'active' NOT NULL, \n\tvisibility VARCHAR(9) DEFAULT 'private' NOT NULL, \n\tcaptured_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_by VARCHAR(100) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_evidence PRIMARY KEY (id), \n\tCONSTRAINT fk_evidence_source_document_id_source_document FOREIGN KEY(source_document_id) REFERENCES source_document (id) ON DELETE RESTRICT, \n\tCONSTRAINT ck_evidence_evidence_status CHECK (status IN ('active', 'locator_invalid', 'archived')), \n\tCONSTRAINT ck_evidence_evidence_visibility CHECK (visibility IN ('public', 'private', 'sensitive'))\n)"))
    op.execute(sa.text('CREATE INDEX ix_evidence_source_document ON evidence (source_document_id)'))
    op.execute(sa.text('CREATE INDEX ix_evidence_status ON evidence (status)'))
    op.execute(sa.text("CREATE TABLE knowledge_relation (\n\tsource_object_id UUID NOT NULL, \n\trelation_type VARCHAR(14) NOT NULL, \n\ttarget_object_id UUID NOT NULL, \n\tepistemic_type VARCHAR(17) NOT NULL, \n\tstatus VARCHAR(10) DEFAULT 'candidate' NOT NULL, \n\tconfidence_note TEXT, \n\tvalid_from TIMESTAMP WITH TIME ZONE, \n\tvalid_to TIMESTAMP WITH TIME ZONE, \n\tcaptured_at TIMESTAMP WITH TIME ZONE, \n\tverified_at TIMESTAMP WITH TIME ZONE, \n\tversion INTEGER DEFAULT '1' NOT NULL, \n\tcreated_by VARCHAR(100) NOT NULL, \n\treviewed_by VARCHAR(100), \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_knowledge_relation PRIMARY KEY (id), \n\tCONSTRAINT ck_knowledge_relation_version_positive CHECK (version >= 1), \n\tCONSTRAINT ck_knowledge_relation_different_endpoints CHECK (source_object_id <> target_object_id), \n\tCONSTRAINT fk_knowledge_relation_source_object_id_knowledge_object FOREIGN KEY(source_object_id) REFERENCES knowledge_object (id) ON DELETE RESTRICT, \n\tCONSTRAINT ck_knowledge_relation_relation_type CHECK (relation_type IN ('has_department', 'offers', 'has_version', 'supersedes', 'requires', 'prefers', 'demonstrates')), \n\tCONSTRAINT fk_knowledge_relation_target_object_id_knowledge_object FOREIGN KEY(target_object_id) REFERENCES knowledge_object (id) ON DELETE RESTRICT, \n\tCONSTRAINT ck_knowledge_relation_epistemic_type CHECK (epistemic_type IN ('direct_fact', 'source_assertion', 'derived_inference', 'personal_judgment')), \n\tCONSTRAINT ck_knowledge_relation_relation_status CHECK (status IN ('candidate', 'confirmed', 'disputed', 'stale', 'superseded', 'archived'))\n)"))
    op.execute(sa.text('CREATE INDEX ix_knowledge_relation_source_type ON knowledge_relation (source_object_id, relation_type)'))
    op.execute(sa.text('CREATE INDEX ix_knowledge_relation_status ON knowledge_relation (status)'))
    op.execute(sa.text('CREATE INDEX ix_knowledge_relation_target_type ON knowledge_relation (target_object_id, relation_type)'))
    op.execute(sa.text("CREATE TABLE claim_basis (\n\tclaim_id UUID NOT NULL, \n\tbasis_kind VARCHAR(10) NOT NULL, \n\tbasis_id UUID NOT NULL, \n\tcreated_by VARCHAR(100) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_claim_basis PRIMARY KEY (id), \n\tCONSTRAINT uq_claim_basis_reference UNIQUE (claim_id, basis_kind, basis_id), \n\tCONSTRAINT fk_claim_basis_claim_id_claim FOREIGN KEY(claim_id) REFERENCES claim (id) ON DELETE RESTRICT, \n\tCONSTRAINT ck_claim_basis_claim_basis_kind CHECK (basis_kind IN ('claim', 'relation', 'preference'))\n)"))
    op.execute(sa.text('CREATE INDEX ix_claim_basis_reference ON claim_basis (basis_kind, basis_id)'))
    op.execute(sa.text("CREATE TABLE decision_basis (\n\tdecision_id UUID NOT NULL, \n\tbasis_kind VARCHAR(10) NOT NULL, \n\tbasis_id UUID NOT NULL, \n\tcreated_by VARCHAR(100) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_decision_basis PRIMARY KEY (id), \n\tCONSTRAINT uq_decision_basis_reference UNIQUE (decision_id, basis_kind, basis_id), \n\tCONSTRAINT fk_decision_basis_decision_id_decision FOREIGN KEY(decision_id) REFERENCES decision (id) ON DELETE RESTRICT, \n\tCONSTRAINT ck_decision_basis_decision_basis_kind CHECK (basis_kind IN ('claim', 'relation', 'preference'))\n)"))
    op.execute(sa.text('CREATE INDEX ix_decision_basis_reference ON decision_basis (basis_kind, basis_id)'))
    op.execute(sa.text("CREATE TABLE evidence_link (\n\tevidence_id UUID NOT NULL, \n\ttarget_kind VARCHAR(15) NOT NULL, \n\ttarget_id UUID NOT NULL, \n\tdirection VARCHAR(9) NOT NULL, \n\tnote TEXT, \n\tcreated_by VARCHAR(100) NOT NULL, \n\tid UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_evidence_link PRIMARY KEY (id), \n\tCONSTRAINT uq_evidence_link_target_direction UNIQUE (evidence_id, target_kind, target_id, direction), \n\tCONSTRAINT fk_evidence_link_evidence_id_evidence FOREIGN KEY(evidence_id) REFERENCES evidence (id) ON DELETE RESTRICT, \n\tCONSTRAINT ck_evidence_link_evidence_target_kind CHECK (target_kind IN ('object', 'relation', 'source_document', 'evidence', 'claim', 'decision', 'candidate')), \n\tCONSTRAINT ck_evidence_link_evidence_direction CHECK (direction IN ('supports', 'refutes', 'qualifies'))\n)"))
    op.execute(sa.text('CREATE INDEX ix_evidence_link_target ON evidence_link (target_kind, target_id)'))


def downgrade() -> None:
    op.execute(sa.text("DROP TABLE IF EXISTS evidence_link CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS decision_basis CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS claim_basis CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS knowledge_relation CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS evidence CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS decision CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS claim CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS candidate CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS source_document CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS processing_job CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS object_version CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS knowledge_object CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS graph_projection_event CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS graph_projection_checkpoint CASCADE"))
    op.execute(sa.text("DROP TABLE IF EXISTS audit_log CASCADE"))
    # pg_trgm may be shared by other schemas, so the extension is intentionally retained.
